import { Briefcase, BrifecaseTick, CallCalling } from "iconsax-react";

import DummyBusiness from "@/assets/img/dummy-business.svg";

export const navItems = [
  {
    id: 1,
    name: "Dashboard",
    link: "/dashboard",
  },
  {
    id: 2,
    name: "Agents",
    link: "/agents",
  },
  {
    id: 3,
    name: "Tickets",
    link: "/tickets",
  },
];

export const dashboardCards = [
  {
    id: 1,
    name: "Total Businesses",
    amount: "1200",
    icon: Briefcase,
  },
  {
    id: 2,
    name: "Active Businesses",
    amount: "500",
    icon: BrifecaseTick,
  },
  {
    id: 3,
    name: "Calls Today",
    amount: "+12,234",
    icon: CallCalling,
  },
];

export const activeBusinesses = [
  {
    id: 1,
    name: "TechSolution Inc.",
    calls: 487,
    logo: DummyBusiness,
  },
  {
    id: 2,
    name: "Global Retail Group",
    calls: 356,
    logo: DummyBusiness,
  },
  {
    id: 3,
    name: "Premier Services LLC",
    calls: 284,
    logo: DummyBusiness,
  },
  {
    id: 4,
    name: "Foodie Enterprises",
    calls: 215,
    logo: DummyBusiness,
  },
  {
    id: 5,
    name: "Urban Healthcare",
    calls: 189,
    logo: DummyBusiness,
  },
];

export const businessesCards = [
  {
    id: 1,
    name: "Total Number of Calls",
    amount: "45,231",
    icon: CallCalling,
  },
  {
    id: 2,
    name: "Number of Success Calls",
    amount: "+2350",
    icon: CallCalling,
  },
  {
    id: 3,
    name: "Number of Failed Calls",
    amount: "+12,234",
    icon: CallCalling,
  },
];

export const voicesMap = {
  vapi: [
    "Elliot",
    "Rohan",
    "Lily",
    "Savannah",
    "Hana",
    "Neha",
    "Cole",
    "Harry",
    "Paige",
    "Spencer",
  ],
  cartesia: [
    "Italian Narrator Woman",
    "Hindi Narrator Man",
    "Polish Narrator Woman",
    "German Reporter Woman",
    "Reading Man",
    "Spanish-speaking Storyteller Man",
    "Indian Lady",
    "Swedish Narrator Man",
    "Confident British Man",
    "Russian Narrator Man 2",
    "Hinglish Speaking Lady",
    "British Customer Support Lady",
    "German Woman",
    "Anime Girl",
    "Korean Narrator Woman",
    "Southern Woman",
    "Middle Eastern Woman",
    "Wise Man",
    "Pleasant Brazilian Lady",
    "New York Man",
    "Newsman",
    "Hindi Reporter Man",
    "Spanish-speaking Lady",
    "French Narrator Man",
    "Japanese Children Book",
    "Hindi Calm Man",
    "Korean Calm Woman",
    "Spanish Narrator Lady",
    "French Conversational Lady",
    "Wise Guide Man",
    "Tutorial Man",
    "Southern Man",
    "Young Spanish-speaking Woman",
    "Australian Male",
    "Laidback Woman",
    "Indian Customer Support Lady",
    "Friendly Reading Man",
    "British Narration Lady",
    "Child",
    "Spanish Narrator Man",
    "ASMR Lady",
    "Commercial Man",
    "Female Nurse",
    "Spanish-speaking Man",
    "Hindi Narrator Woman",
    "Japanese Man Book",
    "Doctor Mischief",
    "Storyteller Lady",
    "German Reporter Man",
    "Indian Man",
    "Chinese Call Center Man",
    "Barbershop Man",
    "Kentucky Woman",
    "British Lady",
    "Customer Support Man",
    "Announcer Man",
    "German Storyteller Man",
    "Professional Woman",
    "New York Woman",
    "Swedish Calm Lady",
    "Maria",
    "German Conversation Man",
    "Friendly German Man",
    "Yogaman",
    "Polish Young Man",
    "Salesman",
    "Movieman",
    "Midwestern Man",
    "Nonfiction Man",
    "Friendly Brazilian Man",
    "Dutch Man",
    "Stern French Man",
    "Teacher Lady",
    "Madame Mischief",
    "Italian Narrator Man",
    "Friendly French Man",
    "Chinese Commercial Man",
    "Sportsman",
    "Italian Calm Man",
    "Chinese Woman Narrator",
    "Korean Narrator Man",
    "Reading Lady",
    "French Narrator Lady",
    "Calm Lady",
    "The Merchant",
    "Calm French Woman",
    "Dutch Confident Man",
    "Turkish Narrator Man",
    "Turkish Calm Man",
    "California Girl",
    "Brazilian Young Man",
    "Japanese Male Conversational",
    "Wise Lady",
    "Russian Narrator Man 1",
  ],
  "11labs": [
    "francotest",
    "test3",
    "test2",
    "test",
    "Bobby.test3",
    "f1",
    "test2",
    "Will",
    "test 44",
    "test 44",
    "Steve - Syfan Dialogue",
    "Callum",
    "test",
    "Bobby.test5",
    "test 44",
    "Nicole",
    "Ethan",
    "Edgar",
    "Bobby.Test8",
    "Bobby.Test4",
    "Aria",
    "test",
    "Hal Elrod",
    "Amara",
    "Beetalia",
    "Amanda Vargas",
    "Derek",
    "MARIA",
    "Olga",
    "Rafa",
    "Test",
    "VozCTX2",
    "sophie",
    "Prefeito",
    "Pedro Braga",
    "Apparently",
    "Charlie",
    "Beth - gentle and nurturing",
    "Bex UK Big T",
    "Knightley Javier -Calm",
    "Giovanni Rossi - giovane",
    "Alex Ozwyn",
    "Bala Conv Test",
    "Kina (Cute happy girl) - Perfect for Social Media & Ads",
    "Kiko Hdz",
    "Kira - authentic storytelling voice",
    "Koray KUTLU",
    "BrittW",
    "CR",
    "Calistria - Enchanting, Refined, Quick-witted",
    "CS New",
    "Luisa",
    "Christopher",
    "Claire - middle age fresh, very realistic",
    "Christina - Calming Yoga Instructor",
    "Avery (Phone)",
    "Lady Dalia - Posh, Youthful, Articulate",
    "Simone",
    "Chase - Animated Childlike Characters",
    "Pierre from Nice",
    "Mahmood",
    "Malena Tango",
    "Manav - Husky, Conversational voice",
    "Schell",
    "Alexa",
    "Jean-Paul Niko",
    "Jennifer - expressive and cheerful narrator",
    "Jeevan - Expressive Indian Voice",
    "MUZAFFER",
    "Maciej Litwiniec - Your best choice.",
    "Madison - snappy",
    "Mad Scientist - For All Languages",
    "MUHAMMER ARABACI - Professional Turkish Voice Over",
    "Magnolia - Mature and Wellspoken",
    "Balazs",
    "Smriti - Indian Storyteller",
    "Soban Ajmal",
    "Sohaib Jasra",
    "Adam Szotkowski",
    "test",
    "Miles Sesame AI",
    "Hassan S",
    "Vaughn",
    "Jess",
    "Liz (Web)",
    "Lina",
    "Dor Levy",
    "Moha",
    "bobby.test",
    "clone voice 123",
    "Julia (Phone)",
    "Dokter Ismy Julianty",
    "CL-VOZ-HOMBRE",
    "GONCALO H DE SOUSA",
    "franco.2",
    "Maevys",
    "Julie",
    "Cal",
    "Fatih Yildirim",
    "Andrew J Griffin",
    "AaaVinci",
    "Ankit Gohel",
    "DR",
    "James",
    "Juan Ignacio",
    "Letizia",
    "Namo",
    "Tay voice 0001",
    "hh",
    "sdasfasfdasdas",
    "steve",
    "Copy of me",
    "ERIC PRIVATE",
    "Vincent - Factual",
    "test",
    "Hélder Santos",
    "SS",
    "SERGIO JUVENAL",
    "Sammy Zimmermanns",
    "Charles 01",
    "Dale Thorn",
    "Miss French - For AUDIOBOOK",
    "iScHbNW8K33gNo3lGgbo",
    "Przemyslaw Krol",
    "Test Suyreh",
    "Wendy",
    "test",
    "Patrick",
    "ARWA",
    "Anjali",
    "Consumer Debt Script",
    "Custom",
    "test",
    "HJS",
    "Emilie Lacroix",
    "Emily - Calm yet charismatic",
    "Emma",
    "Pratama",
    "Olivia",
    "1234test1234",
    "06Aditi",
    "Ravi Shankar",
    "Razvan Ogrezeanu",
    "Real test voice",
    "RealMadrid",
    "SingFeb",
    "James Mirko",
    "James Gao",
    "Mia Chou",
    "female",
  ],
  "rime-ai": [
    "eva",
    "kendrick",
    "gerald",
    "gulch",
    "joy",
    "rob",
    "alona",
    "madison",
    "rosco",
    "marsh",
    "flower",
    "rohan",
    "brittany",
    "rex",
    "bayou",
    "reba",
    "spore",
    "alpine",
    "tibur",
    "boulder",
    "kevin",
    "brook",
    "juan",
    "creek",
    "selena",
    "glacier",
    "elliot",
    "hera",
    "colin",
    "cove",
    "samantha",
    "tundra",
    "courtney",
    "carol",
    "elena",
    "yadira",
    "lagoon",
    "grove",
  ],
  playht: [
    "Taylor",
    "Davis",
    "Melissa",
    "William (Narrative)",
    "Eileen",
    "Frederick",
    "Hook",
    "Samara",
    "William (Training)",
    "Charlotte (Narrative)",
    "Michael",
    "Chris",
    "Ozer",
    "male",
    "Aaliyah",
    "Pia",
    "Ayla (Expressive)",
    "Navya",
    "Oliver (Training)",
    "Indigo",
    "Oliver (Narrative)",
    "Isabella",
    "Calvin",
    "Charles",
    "Charlotte (Training)",
    "Hook",
    "Leroy",
    "Amelia",
    "Sarge",
    "Olivia (Narrative)",
    "Susan (Training)",
    "Arthur (Meditation)",
    "Madelyn",
    "Nolan",
    "Hudson",
    "Alessandro",
    "Eleanor",
    "Micah",
    "Atlas",
    "Waylon",
    "Teddy",
    "Audrey",
    "Charlotte (Meditation)",
    "Charlotte",
    "Donna (Narrative)",
    "Sarge",
    "Ranger",
    "Oliver (Advertising)",
    "Will",
    "Russell",
    "Elon",
    "Jack",
    "Clark",
    "Ruby",
    "Joseph",
    "Alfonso",
    "Donna (Meditation)",
    "Finley",
    "Adelaide",
    "Arthur (Training)",
    "Wilbur",
    "Larry (Narrative)",
    "Evelyn",
    "Logan",
    "Lance",
    "Ayla (Training)",
    "Larry (Advertising)",
    "Arthur (Advertising)",
    "Harris",
    "Oliver (Training)",
    "Autumn",
    "Chuck",
    "Dudley",
    "Adolfo",
    "Theodore",
    "Larry",
    "Alex",
    "Earle",
    "Niamh",
    "Matt",
    "Flynn",
    "Mark",
    "Frankie",
    "Susan (Narrative)",
    "Donovan",
    "Dick",
    "William (Training)",
    "Oliver",
    "Ayla (Advertising)",
    "Nova",
    "Ayla (Narrative)",
    "Darrell",
    "Susan (Narrative)",
    "Sumita",
    "Lachlan",
    "Hunter",
    "Axel",
    "Charlotte (Advertising)",
    "Arthur (Narrative)",
    "Carmen",
    "Dylan",
    "Owen",
    "Madison",
    "Nigel",
    "Susan (Narrative)",
    "Billy",
    "Susan (Advertising)",
    "Susan (Training)",
    "Mason",
    "Sophia",
    "Arthur (Narrative)",
    "Mitch",
    "Billy",
    "Archie",
    "William (Narrative)",
    "Clifton",
    "Wilbert",
    "Olivia (Advertising)",
    "April",
    "Samuel",
    "Nicole",
    "Anthony",
    "Abigail",
    "Benton",
    "Charlotte (Narrative)",
    "Eileen",
    "Carter",
    "Adrian",
    "Ayla (Meditation)",
    "Siobhán",
    "William",
    "Baptiste",
    "Ayla (Meditation)",
    "Aurora",
    "Arthur (Meditation)",
    "Darnell",
    "Arthur (Training)",
    "Barry (Advertising)",
    "Arthur",
    "Larry (Narrative)",
    "Delilah",
    "Phoebe",
    "George",
    "Scarlett",
    "Olivia (Advertising)",
    "Lumi",
    "Abigail",
    "Ada",
    "mAyla (Narrative)",
    "Barry (Narrative)",
    "Nolan",
  ],
  lmnt: [
    "Lily",
    "Curtis",
    "Caleb",
    "Noah",
    "Morgan",
    "Sophie",
    "Lauren",
    "Natalie",
    "Oliver",
    "Kathrine",
    "Olivia",
    "Magnus",
    "Zeke",
    "Chloe",
    "Reba",
    "Zain",
    "Ava",
    "Miles",
    "Paige",
    "Maurice",
    "Marzia",
    "Szymon",
    "Eleanor",
    "Terrence",
    "James",
    "Dalton",
    "Daniel",
    "Ethel",
    "Henry",
    "Giuseppe",
    "Amy",
    "Nathan",
    "Oliver",
    "Joe",
    "Donna",
    "Zoe",
    "Beatriz",
    "Priya",
  ],
  deepgram: [
    "Athena",
    "Arcas",
    "Zeus",
    "Perseus",
    "Asteria",
    "Luna",
    "Orpheus",
    "Helios",
    "Stella",
    "Orion",
    "Hera",
    "Angus",
  ],
  openai: ["fable", "echo", "alloy", "shimmer", "onyx", "nova"],
  azure: [
    "Zuri",
    "Lia",
    "Andrea",
    "Xiaorou",
    "Ezinne",
    "Rafiki",
    "Pierina",
    "Ona",
    "Juan",
    "Elsa",
    "Elke",
    "Ameha",
    "Eloise",
    "Fernanda",
    "Neil",
    "Ashley",
    "Tony",
    "Layla",
    "Xiaotong",
    "Nuria",
    "Maurice",
    "Ryan",
    "Camila",
    "Abeo",
    "Ojas",
    "Saul",
    "Celeste",
    "Gul",
    "Ahmet",
    "Henri",
    "Katja",
    "Polina",
    "Ainhoa",
    "Annette",
    "Tania",
    "Noemi",
    "Rana",
    "Yunyang",
    "Clara",
    "Antonin",
    "Ander",
    "Mario",
    "Bataa",
    "Gerard",
    "Candela",
    "Sreymom",
    "Abril",
    "Elza",
    "Libby",
    "Dhwani",
    "Giuseppe",
    "Sam",
    "Asilia",
    "SoonBok",
    "Sylvie",
    "Blue",
    "Alvaro",
    "Aashi",
    "Sebastian",
    "Mattias",
    "Christoph",
    "Kumar",
    "Noora",
    "Nicolau",
    "Sapna",
    "Jorge",
    "William",
    "Colette",
    "James",
    "Lukas",
    "Ubax",
    "Nil",
    "Monica",
    "Siti",
    "Tomas",
    "Nicholas",
    "Sameera",
    "Harri",
    "Sagar",
    "Kert",
    "Avri",
    "Yan",
    "Hemkala",
    "Anu",
    "Priyom",
    "Uzma",
    "Gabrijela",
    "Omar",
    "Nancy",
    "Valluvar",
    "Laia",
    "Ken",
    "Kavya",
    "Yashica",
    "Irma",
    "Aled",
    "Asad",
    "Ostap",
    "Alain",
    "Hyunsu",
    "Cora",
    "Thiha",
    "Sara",
    "Isabella",
    "Nils",
    "Claude",
    "Elimu",
    "Bella",
    "HiuGaai",
    "NamMinh",
    "Yves",
    "Finn",
    "Jane",
    "Sofia",
    "Jason",
    "Everita",
    "Mia",
    "Dario",
    "Alonso",
    "InJoon",
    "Viktoria",
    "Leah",
    "Pelayo",
    "Naoki",
    "Srecko",
    "Andrew",
    "Natasha",
    "Noura",
    "Francisca",
    "Petra",
    "Marcelo",
    "Shiori",
    "Paloma",
    "Thalita",
    "Rehaan",
    "Xiaoqiu",
    "Mayu",
    "Moaz",
    "HoaiMy",
    "Dmitry",
    "Sophie",
    "Niranjan",
    "Achara",
    "Aarohi",
    "Emma Multilingual",
    "Amal",
    "Roger",
    "Marta",
    "Jean",
  ],
  hume: [
    "Shawn Smote",
    "Formal English Storyteller",
    "New Age Surfer Dude",
    "Sarcastic Londoner",
    "Scottish Guy",
    "Amateur Remodeler",
    "Old School Radio Announcer",
    "Donovan Sinclair",
    "Wrestling Announcer",
    "Dr. Angelina Brooks",
    "Unserious TV Host",
    "Dungeon Master",
    "Old-Timey English Priest",
    "Lady Elizabeth",
    "Medieval Peasant Man",
    "Friendly Troll",
    "Melodic English Man",
    "Pirate Captain",
    "Serious Movie Trailer Narrator",
    "Female Meditation Guide",
    "Shouting Voice",
    "Terrence Bentley",
    "Obnoxious Prince",
    "Sad Old British Man",
    "Scurvey-Ridden First Mate",
    "Charming Cowboy",
    "Nasal Podcast Host",
    "Imani Carter",
    "Relaxing ASMR Woman",
    "Alice Bennett",
    "Medieval Peasant Woman",
    "Evil Undead Vampire",
    "Whispering Guy",
    "Charming Cowgirl",
    "Medieval Town Crier",
    "Mrs. Pembroke",
    "Cool Nerd",
    "Sitcom Girl",
    "Sebastian Lockwood",
    "Male Protagonist",
    "Geraldine Walalce",
    "Nature Documentary Narrator",
    "Unserious Movie Trailer Narrator",
    "Ghost With Unfinished Business",
    "Wise Wizard",
  ],
  sesame: [
    "Elliot",
    "Cole",
    "Hana",
    "Harry",
    "Lily",
    "Neha",
    "Paige",
    "Rohan",
    "Savannah",
    "Spencer",
  ],
};
